import { db } from '../../lib/db';
import { requireUser, hashPassword } from '../../lib/session';

export const dynamic='force-dynamic';

async function createUser(formData:FormData){'use server';const actor=await requireUser();if(actor.role!=='owner'&&actor.role!=='admin')return;const email=String(formData.get('email')||'').trim().toLowerCase();const name=String(formData.get('name')||'').trim();const password=String(formData.get('password')||'');const role=String(formData.get('role')||'operator');if(!email||!name||password.length<12||!['admin','operator','viewer'].includes(role))return;const {hash,salt}=hashPassword(password);const result=await db().query(`insert into users(email,password_hash,password_salt,display_name,role) values($1,$2,$3,$4,$5) returning id`,[email,hash,salt,name,role]);await db().query(`insert into audit_events(actor_user_id,actor,action,resource_type,resource_id,details) values($1,$2,'user.create','user',$3,$4)`,[actor.id,actor.email,result.rows[0].id,JSON.stringify({email,role})]);}

async function toggleUser(formData:FormData){'use server';const actor=await requireUser();if(actor.role!=='owner'&&actor.role!=='admin')return;const id=String(formData.get('id')||'');if(!id||id===actor.id)return;await db().query(`update users set status=case when status='active' then 'disabled' else 'active' end where id=$1 and role <> 'owner'`,[id]);}

export default async function Users(){const actor=await requireUser();const users=(await db().query('select id,email,display_name,role,status,last_login_at,created_at from users order by created_at')).rows;return <div className="shell"><aside className="side"><div className="brand">License Manager</div><nav className="nav"><a href="/">Overview</a><a href="/licenses">Licenses</a><a href="/products">Products</a><a href="/releases">Releases</a><a href="/users" className="active">Users</a><a href="/settings">System Settings</a><a href="/api-docs">API Contract</a></nav></aside><main className="main"><h1 className="title">Users</h1><p className="muted">Accounts are stored and authenticated by this License Manager. There is no external identity dependency.</p>{['owner','admin'].includes(actor.role)&&<div className="section card"><form className="form" action={createUser}><label>Name<input className="input" name="name" required/></label><label>Email<input className="input" type="email" name="email" required/></label><label>Temporary password<input className="input" type="password" name="password" minLength={12} required/></label><label>Role<select className="input" name="role"><option value="admin">Admin</option><option value="operator">Operator</option><option value="viewer">Viewer</option></select></label><button className="button">Create user</button></form></div>}<div className="section"><table className="table"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Last sign in</th><th></th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.display_name}</td><td>{u.email}</td><td>{u.role}</td><td><span className={`badge ${u.status==='active'?'ok':'off'}`}>{u.status}</span></td><td>{u.last_login_at?new Date(u.last_login_at).toLocaleString():'Never'}</td><td>{u.role!=='owner'&&['owner','admin'].includes(actor.role)&&<form action={toggleUser}><input type="hidden" name="id" value={u.id}/><button className="button secondary">{u.status==='active'?'Disable':'Enable'}</button></form>}</td></tr>)}</tbody></table></div></main></div>}
