import {requireUser} from '../../lib/session';
import {listApiKeys,createApiKey,revokeApiKey,deleteRevokedApiKey,ApiScope} from '../../lib/core/api-keys';
import ApiKeyForm from './form';
import SideNav from '../components/SideNav';
import PageHeader from '../components/PageHeader';
export const dynamic='force-dynamic';
const scopes:ApiScope[]=['license.issue','license.validate','license.manage','releases.read','releases.write','deployment.read','deployment.write'];
async function create(formData:FormData){'use server';const u=await requireUser();if(!['owner','admin'].includes(u.role))return;const name=String(formData.get('name')||'').trim();const selected=String(formData.get('scopes')||'').split(',').filter((x):x is ApiScope=>scopes.includes(x as ApiScope));if(!name||!selected.length)return;const result=await createApiKey({name,scopes:selected,actorUserId:u.id});return result.key;}
async function revoke(formData:FormData){'use server';const u=await requireUser();if(!['owner','admin'].includes(u.role))return;const id=String(formData.get('id')||'');if(id)await revokeApiKey(id,u.id);}
async function deleteRevoked(formData:FormData){'use server';const u=await requireUser();if(!['owner','admin'].includes(u.role))return;const id=String(formData.get('id')||'');if(id)await deleteRevokedApiKey(id,u.id);}
export default async function ApiKeys(){const u=await requireUser();const keys=await listApiKeys();return <div className="shell"><SideNav active="api-keys"/><main className="main"><PageHeader eyebrow="System / Access" title="API Access" description="Machine credentials for Billing Store, release builders and deployment clients. Each integration should use its own least-privilege key." badge={String(keys.length)}/><section className="card form-card"><div><div className="eyebrow">Machine credentials</div><h2>Create integration key</h2></div>{['owner','admin'].includes(u.role)?<ApiKeyForm action={create} scopes={scopes}/>:<div className="notice">Only Owner and Admin accounts can create or revoke integration keys.</div>}</section><section className="section"><div className="section-head"><div><div className="eyebrow">Credential inventory</div><h2>Managed keys</h2><p className="muted">Only the last four characters are displayed after creation.</p></div></div><div className="table-shell"><table className="table"><thead><tr><th>Name</th><th>Key</th><th>Scopes</th><th>Status</th><th>Last used</th><th>Control</th></tr></thead><tbody>{keys.map((k:any)=><tr key={k.id}><td><strong>{k.name}</strong></td><td className="mono">lm_••••{k.key_last4}</td><td>{(k.scopes as string[]).join(', ')}</td><td><span className={k.status==='active'?'state-pill online':'state-pill offline'}>{k.status}</span></td><td>{k.last_used_at?new Date(k.last_used_at).toLocaleString():'Never'}</td><td>{['owner','admin'].includes(u.role)&&<>{k.status==='active'&&<form action={revoke}><input type="hidden" name="id" value={k.id}/><button className="button danger">Revoke</button></form>}{k.status==='revoked'&&<form action={deleteRevoked}><input type="hidden" name="id" value={k.id}/><button className="button danger">Delete</button></form>}</>}</td></tr>)}</tbody></table></div></section></main></div>}
