import { requireUser } from '../../../lib/session';
import { listReleases, setReleaseReview, publishRelease, validateRelease } from '../../../lib/core/releases';
import SideNav from '../../components/SideNav';

export const dynamic='force-dynamic';
const roles=['owner','admin','operator'];

async function validate(formData:FormData){'use server';const user=await requireUser();if(!roles.includes(user.role))return;const id=String(formData.get('id')||'');if(id)await validateRelease(id,user.id,user.email);}
async function review(formData:FormData){'use server';const user=await requireUser();if(!roles.includes(user.role))return;const id=String(formData.get('id')||'');const decision=String(formData.get('decision')||'');if(id&&(decision==='approved'||decision==='rejected'))await setReleaseReview(id,decision,user.id,user.email);}
async function sendToCustomer(formData:FormData){'use server';const user=await requireUser();if(!['owner','admin'].includes(user.role))return;const id=String(formData.get('id')||'');if(id)await publishRelease(id,user.id,user.email);}

function validationSummary(r:any){const v=r.manifest?.validation;if(!v)return {status:'not run',checks:[]};return {status:v.status||'failed',checks:Array.isArray(v.checks)?v.checks:[]};}

export default async function BaseDeployment(){
 const user=await requireUser();
 const releases=(await listReleases()).filter((r:any)=>r.release_type==='base');
 return <div className="shell"><SideNav active="base"/><main className="main">
  <div className="row" style={{justifyContent:'space-between',alignItems:'flex-start'}}><div><div className="muted" style={{textTransform:'uppercase',letterSpacing:'.08em'}}>Base Release Authority</div><h1 className="title">Base Deployment</h1><p className="muted">GitHub creates the Base candidate. License Master captures, validates and reviews the complete package. Final publication sends the approved Base release to the customer portal; License Master does not deploy a customer Vercel project.</p></div><span className="badge">BASE ONLY</span></div>
  <section className="section card"><h2>Manual release flow</h2><div className="listrow"><div style={{flex:1}}><strong>1 · GitHub job</strong><span>Run after the Base branch is merged.</span></div></div><div className="listrow"><div style={{flex:1}}><strong>2 · Automatic intake</strong><span>Package, generated changelog, manifest, checksum and CI metadata are captured.</span></div></div><div className="listrow"><div style={{flex:1}}><strong>3 · Validate &amp; review</strong><span>License Master scans the artifact and records every validation result.</span></div></div><div className="listrow"><div style={{flex:1}}><strong>4 · Send to Customer Portal</strong><span>Admin publishes the approved Base release for the customer's Base Deployer.</span></div></div></section>
  <section className="section card"><h2>Base release queue</h2>{releases.length?releases.map((r:any)=>{const v=validationSummary(r);const reviewable=r.status!=='published'&&v.status==='passed';return <div className="listrow" key={r.id}><div style={{minWidth:0,flex:1}}><strong>OrbitFS Base {r.version}</strong><span>{r.status} · review {r.review_status} · validation {v.status}</span><small>Source: {r.source_repo||'—'} @ {r.source_ref||'—'}</small><small>Commit: {r.source_sha||'—'}</small><small>Artifact: {r.artifact_name||'—'} · CI run {r.artifact_run_id||'—'}</small><small style={{whiteSpace:'pre-wrap'}}>{r.notes||'No generated changelog recorded.'}</small>{v.checks.length?<details><summary>Validation report</summary><div style={{display:'grid',gap:4,marginTop:8}}>{v.checks.map((c:any)=><small key={c.key}>{c.ok?'PASS':'FAIL'} · {c.message}</small>)}</div></details>:null}</div><div className="actions">{r.status!=='published'&&<form action={validate}><input type="hidden" name="id" value={r.id}/><button className="button">Validate / scan</button></form>}{r.review_status==='pending'&&<><form action={review}><input type="hidden" name="id" value={r.id}/><input type="hidden" name="decision" value="approved"/><button className="button" disabled={!reviewable}>Approve Base</button></form><form action={review}><input type="hidden" name="id" value={r.id}/><input type="hidden" name="decision" value="rejected"/><button className="button">Reject</button></form></>}{r.review_status==='approved'&&r.status!=='published'&&['owner','admin'].includes(user.role)&&<form action={sendToCustomer}><input type="hidden" name="id" value={r.id}/><button className="button">Send to Customer Portal</button></form>}</div></div>}) : <p className="muted">No Base release candidates have been captured yet. Run the V1-vercel-base GitHub release job.</p>}</section>
 </main></div>;
}
