import Link from 'next/link';
import {db} from '../lib/db';
import {requireUser} from '../lib/session';
import SideNav from './components/SideNav';
import PageHeader from './components/PageHeader';
export const dynamic='force-dynamic';
async function stats(){const p=db();const [licenses,products,published,pending,failed,activations,settings]=await Promise.all([
 p.query("select count(*)::int count from licenses"),
 p.query("select count(*)::int count from products where status <> 'archived'"),
 p.query("select count(*)::int count from releases where status='published'"),
 p.query("select count(*)::int count from releases where status <> 'published' and review_status='pending' and archived_at is null"),
 p.query("select count(*)::int count from releases where coalesce((manifest->'validation'->>'status'),'not_run')='failed' and archived_at is null"),
 p.query("select count(*)::int count from activations where status='active'"),
 p.query("select system_enabled,licensing_enabled,release_system_enabled,deployment_enabled,maintenance_mode from system_settings where id=true")
]);return {licenses:licenses.rows[0].count,products:products.rows[0].count,published:published.rows[0].count,pending:pending.rows[0].count,failed:failed.rows[0].count,activations:activations.rows[0].count,settings:settings.rows[0]};}
export default async function Home(){await requireUser();const s=await stats();const online=Boolean(s.settings?.system_enabled);const switches=[['Licensing',s.settings?.licensing_enabled],['Releases',s.settings?.release_system_enabled],['Base deployment',s.settings?.deployment_enabled],['Maintenance',s.settings?.maintenance_mode]];
return <div className="shell"><SideNav active="overview"/><main className="main"><PageHeader eyebrow="Authority Control Plane" title="Operations Overview" description="A single operating view for licensing, installation state, release validation and controlled publication." badge={online?'ONLINE':'OFFLINE'}/>
<div className="grid"><Link href="/licenses" className="card link-card"><div className="muted">Licenses</div><div className="metric">{s.licenses}</div><div>Open licensing →</div></Link><Link href="/installations" className="card link-card"><div className="muted">Active installations</div><div className="metric">{s.activations}</div><div>Inspect fleet →</div></Link><Link href="/releases" className="card link-card"><div className="muted">Release candidates</div><div className="metric">{s.pending}</div><div>Work the queue →</div></Link><Link href="/releases" className="card link-card"><div className="muted">Validation failures</div><div className="metric">{s.failed}</div><div>Resolve blockers →</div></Link></div>
<div className="detail-grid section"><section className="card"><div className="row" style={{justifyContent:'space-between',alignItems:'center'}}><div><h2>System posture</h2><p className="muted">Current authority switches are read directly from the control plane.</p></div><span className="badge">{s.settings?.maintenance_mode?'MAINTENANCE':'NORMAL'}</span></div><div className="posture-grid">{switches.map(([label,value])=><div className="posture-row" key={String(label)}><span>{String(label)}</span><span className={value?'badge ok':'badge off'}>{value?'Enabled':'Disabled'}</span></div>)}</div></section>
<section className="card"><h2>What happens here</h2><div className="timeline-mini"><div><b>1</b><span><strong>Builds arrive</strong><small>Base and Engine workflows submit immutable release metadata.</small></span></div><div><b>2</b><span><strong>License Manager checks</strong><small>Integrity, manifest, source, CI and package checks run here.</small></span></div><div><b>3</b><span><strong>Technical approval</strong><small>Approval only happens after validation passes.</small></span></div><div><b>4</b><span><strong>Billing Store publishes</strong><small>Customer-facing publication remains a separate gate.</small></span></div></div></section></div>
<div className="section card"><div className="row" style={{justifyContent:'space-between',alignItems:'center'}}><div><h2>Operations</h2><p className="muted">Jump directly into the part of the authority you are operating.</p></div></div><div className="quick-grid"><Link className="button" href="/releases/base">Base Deployment</Link><Link className="button" href="/releases">Release Updates</Link><Link className="button secondary" href="/licenses">Licensing</Link><Link className="button secondary" href="/installations">Installations</Link><Link className="button secondary" href="/settings">System Settings</Link></div></div>
</main></div>}
