import {requireUser} from '../../../lib/session';
import {listReleaseChannels,saveReleaseChannel} from '../../../lib/core/release-channels';
import SideNav from '../../components/SideNav';
import PageHeader from '../../components/PageHeader';
import LiveRefresh from '../../components/LiveRefresh';
export const dynamic='force-dynamic';
const roles=['owner','admin'];
async function save(formData:FormData){'use server';const user=await requireUser();if(!roles.includes(user.role))return;await saveReleaseChannel({channel:String(formData.get('channel')||''),label:String(formData.get('label')||''),description:String(formData.get('description')||''),enabled:formData.get('enabled')==='on',customerVisible:formData.get('customer_visible')==='on',sortOrder:Number(formData.get('sort_order')||100),actorUserId:user.id,actor:user.email});}
export default async function ReleaseChannels(){const user=await requireUser();const channels=await listReleaseChannels(true);return <div className="shell"><SideNav active="channels"/><main className="main"><PageHeader eyebrow="Release Operations / Authority" title="Release Channels" description="Authoritative channel definitions used by the Base and Engine release jobs. Billing Store controls customer access, not channel creation." badge="MASTER"/><div className="channel-grid">{channels.map((c:any)=><section className="card channel-card" key={c.id}><div className="row" style={{justifyContent:'space-between',alignItems:'center'}}><div><h2>{c.label}</h2><span className="badge">{c.channel}</span></div><LiveRefresh/></div><p className="muted">{c.description||'No description.'}</p><div className="channel-flags"><span className={c.enabled?'badge ok':'badge off'}>{c.enabled?'Enabled':'Disabled'}</span><span className="badge">{c.customer_visible?'Customer visible':'Internal'}</span></div>{roles.includes(user.role)&&<form className="form" action={save}><input type="hidden" name="channel" value={c.channel}/><label>Label<input className="input" name="label" defaultValue={c.label}/></label><label>Description<textarea className="input" name="description" defaultValue={c.description} rows={3}/></label><div className="inline-fields"><label>Sort order<input className="input" name="sort_order" defaultValue={c.sort_order} inputMode="numeric"/></label><label className="check-option"><input type="checkbox" name="enabled" defaultChecked={c.enabled}/><span>Enabled</span></label><label className="check-option"><input type="checkbox" name="customer_visible" defaultChecked={c.customer_visible}/><span>Customer visible</span></label></div><button className="button">Save changes</button></form>}</section>)}</div>{roles.includes(user.role)&&<section className="section card"><h2>Add channel</h2><form className="form form-grid-3" action={save}><label>Channel key<input className="input" name="channel" placeholder="internal-canary" required/></label><label>Label<input className="input" name="label" placeholder="Internal Canary" required/></label><label>Description<input className="input" name="description"/></label><input type="hidden" name="sort_order" value="100"/><label className="check-option"><input type="checkbox" name="enabled" defaultChecked/><span>Enabled</span></label><label className="check-option"><input type="checkbox" name="customer_visible" defaultChecked/><span>Customer visible</span></label><button className="button">Create channel</button></form></section>}</main></div>}
