import {mkdirSync,rmSync,writeFileSync,existsSync,readFileSync} from "node:fs";
import {spawnSync} from "node:child_process";
const dir=".orbitfs-validation"; rmSync(dir,{recursive:true,force:true}); mkdirSync(dir,{recursive:true});
const npm=process.platform==="win32"?"npm.cmd":"npm"; const failures=[];
const run=(label,command,args,fix,prompt)=>{console.log("\n=== "+label+" ===");const r=spawnSync(command,args,{encoding:"utf8",shell:false});const output=[r.stdout||"",r.stderr||""].join("\n").trim();if(r.status!==0){failures.push({label,exitCode:r.status??1,output:output.slice(-12000),fix,prompt});console.error(output);return false;}return true;};
if(!existsSync("package-lock.json")) failures.push({label:"Repository / lockfile",exitCode:1,output:"package-lock.json is missing.",fix:"Restore and commit the lockfile.",prompt:"Fix the missing package-lock.json. Keep dependencies locked, then run npm ci, lint, typecheck and build."});
if(!existsSync("vercel.json")) failures.push({label:"Vercel configuration",exitCode:1,output:"vercel.json is missing.",fix:"Restore the required production vercel.json.",prompt:"Fix the missing vercel.json using the existing production configuration. Do not change unrelated settings, then run the full validation."});
else { try { const v=JSON.parse(readFileSync("vercel.json","utf8")); if(v?.git?.deploymentEnabled!==false) failures.push({label:"Automatic Vercel deployments",exitCode:1,output:"vercel.json does not disable automatic Git deployments.",fix:"Set git.deploymentEnabled to false.",prompt:"Fix vercel.json so automatic Vercel Git deployments are disabled. Do not alter unrelated deployment settings. Then run the full validation."}); } catch(e) { failures.push({label:"Vercel configuration",exitCode:1,output:String(e),fix:"Fix invalid vercel.json JSON.",prompt:"Fix the JSON syntax in vercel.json with the smallest production-safe change, then run the full validation."}); } }
run("Clean locked dependency install",npm,["ci"],"Fix the dependency/lockfile state so npm ci succeeds.","Fix the dependency installation failure. Inspect package.json and package-lock.json, make the smallest safe correction, then run npm ci, lint, typecheck and build.");
run("Whitespace / patch integrity","git",["diff","--check"],"Fix the reported whitespace or patch-integrity errors.","Fix the git diff --check failures without changing unrelated code, then rerun validation.");
run("Lint",npm,["run","lint"],"Fix the reported lint errors.","Fix the reported lint errors in the exact files/lines shown, then rerun lint, typecheck and build.");
run("Typecheck",npm,["run","typecheck"],"Fix the reported TypeScript/type errors.","Fix the reported TypeScript errors in the exact files/lines shown, then rerun typecheck and build.");
run("Dependency audit",npm,["audit","--audit-level=high"],"Resolve or remediate the high-severity dependency findings.","Fix the high-severity dependency audit findings with the smallest safe dependency/remediation change, preserve the lockfile, and rerun validation.");
run("Production build",npm,["run","build"],"Fix the production build error shown in this report.","Fix the production build failure by inspecting the exact error and affected code/configuration. Make the smallest production-safe change, then rerun the full validation.");
if(failures.length){const lines=["ORBITFS VALIDATION FAILED","========================","Temporary report for this validation run.","","Failures: "+failures.length,""];for(const f of failures){lines.push("## "+f.label,"Exit code: "+f.exitCode,"","ERROR:",f.output||"(no command output)","","SUGGESTED FIX:",f.fix,"","PROMPT:",f.prompt,"");}writeFileSync(dir+"/validation-error.txt",lines.join("\n"));console.error("\nValidation failed. Report: "+dir+"/validation-error.txt");process.exit(1);}
rmSync(dir,{recursive:true,force:true}); console.log("\n=== Preflight PASSED ===");