import {requireUser} from '../../lib/session';
import {createProduct,listProducts,setProductStatus} from '../../lib/core/products';
import SideNav from '../components/SideNav';
import PageHeader from '../components/PageHeader';
import TableTools from '../components/TableTools';
export const dynamic='force-dynamic';
async function create(formData:FormData){'use server';const user=await requireUser();if(!['owner','admin'].includes(user.role))return;const name=String(formData.get('name')||'').trim();const slug=String(formData.get('slug')||'').trim().toLowerCase();if(!name||!slug)return;await createProduct({name,slug,description:String(formData.get('description')||'')||null,actorUserId:user.id,actor:user.email});}
async function status(formData:FormData){'use server';const user=await requireUser();if(!['owner','admin'].includes(user.role))return;const id=String(formData.get('id')||'');const value=String(formData.get('status')||'disabled') as 'active'|'disabled'|'archived';if(['active','disabled','archived'].includes(value))await setProductStatus(id,value,user.id,user.email);}
export default async function Products(){const user=await requireUser();const products=await listProducts();const statuses=[...new Set(products.map((x:any)=>x.status))];return <div className="shell"><SideNav active="products"/><main className="main"><PageHeader eyebrow="System / Products" title="Products" description="Define the product identities that the License Manager can license and validate." badge={String(products.length)}/>{['owner','admin'].includes(user.role)&&<section className="card form-card"><div><h2>Create product</h2><p className="muted">Add a product before a release or license can reference it.</p></div><form className="form form-grid-3" action={create}><label>Name<input className="input" name="name" required/></label><label>Slug<input className="input" name="slug" placeholder="orbitfs" pattern="[a-z0-9][a-z0-9._-]*" required/></label><label>Description<input className="input" name="description"/></label><button className="button">Create product</button></form></section>}<section className="section"><TableTools targetId="product-table" filters={statuses}/><div className="table-shell" id="product-table"><table className="table"><thead><tr><th>Product</th><th>Slug</th><th>Status</th><th>Created</th><th>Control</th></tr></thead><tbody>{products.map((p:any)=><tr key={p.id} data-row data-filter={p.status} data-search={`${p.name} ${p.slug} ${p.description||''} ${p.status}`}><td><strong>{p.name}</strong><small className="muted" style={{display:'block'}}>{p.description||'No description'}</small></td><td className="mono">{p.slug}</td><td><span className={p.status==='active'?'badge ok':'badge off'}>{p.status}</span></td><td>{new Date(p.created_at).toLocaleString()}</td><td>{['owner','admin'].includes(user.role)&&p.status!=='archived'&&<form action={status}><input type="hidden" name="id" value={p.id}/><input type="hidden" name="status" value={p.status==='active'?'disabled':'active'}/><button className="button secondary">{p.status==='active'?'Disable':'Enable'}</button></form>}</td></tr>)}</tbody></table></div></section></main></div>}
